### ISSUE TITLE
Extend selection limit

### ISSUE THREAD

**Issue by mazayy** [microsoft/vsts-extension-multivalue-control#211]
We have an use case where we need to select more than 32 elements in the picklist.
In this case control shows error message and is work item cannot be saved.

Error message: "Set the field Component_deng_pls to use suggested values rather than allowed values. [See documentation](https://github.com/Microsoft/vsts-extension-multivalue-control#azure-devops-services)"

Thank you.

**Comment by madkoo** [comment]
Thanks for the feedback. There is a character limit on the filed of 255 char, thats why you probably cannot select all of those items. 
A workaround would be to choose a https://docs.microsoft.com/en-us/rest/api/azure/devops/processes/fields?view=azure-devops-rest-6.0

**Comment by madkoo** [comment]
Thanks for the feedback. It's caused by a limitation in the work item field type (picklist/string) together with how the extension stores the data (a delimited string) the field length limit is 255 chars.
A possible solution would be to use a Text/multiline field + configure the set of values in the multi select custom control instead of using a picklist/string field,

**Comment by viveksahece** [comment]
same with me
![image](https://user-images.githubusercontent.com/79016991/191681829-c0467a78-0a3d-4cfb-a38f-0691b31f23fc.png)
