### ISSUE TITLE
Filtering is Case Sensitive

### ISSUE THREAD

**Issue by sco-owe** [microsoft/vsts-extension-multivalue-control#236]
The changes for #219 now mean that filtering is case sensitive, this has led to a lot of confusion within my team.

Also, trying to remember the exact casing of each item is cumbersome.

**Comment by AminTi** [comment]
HI!, the value should be case-sensitive. I will fix the filter as soon as possible.

**Comment by mammothwizard** [comment]
Hi, I also found it surprising. Does it mean you'd enable turning case sensitivity on/off in the extension settings or how do you plan to fix the filter? Thanks in advance for any info.

**Comment by vfortin02** [comment]
Hello, I've had multiple users within our company's organization confused by the sudden change of behaviour of the extension last month which has caused friction, therefore I support @mammothwizard's suggestion.

**Comment by levaikrisztian-evo** [comment]
Hi! This makes searching for values much worse, especially because Azure DevOps does not let the globallist's values be changed once they have been added. For example if I first added value as "VALUE1" then I can not change it to "value1" in the globallist listitems.

**Please make it configurable at least!**

I'm speaking on behalf of our whole organization of thousands of users!
